XcodebuildConfiguration: Add other-flags param
mercadolibre/arcanist-extensions pull request #2
Opened 2017-08-10 19:51 UTC by nsuarezml

Removed default param `-dry-run`. Now is parametrizable from `.arcconfig`

```
{
    "project_id" : "MLUI",
    "load": [
        "/usr/local/opt/arc-lint"
    ],
    "xcodebuild.workspace": "MLUI.xcworkspace",
    "xcodebuild.scheme": "MLUIApp",
    "xcodebuild.other-flags": "-dry-run"
}
```

For projects with dynamic frameworks is necessary build the project, but OCLint can't resolve some imports.

2017-08-11 04:21 UTC, jsotuyod requested changes
Por otro lado, si bien entiendo que necesites sacar el flag, no me copa que cambiemos el default para todo el mundo... quizás lo correcto sería que el default siga siendo el dry-run, pero se pueda apagar. Esto podrías lograrlo incluso con `$config->getConfigFromAnySource()`, que te permite dar un default a una config sí y sólo sí, esa config no está explícitamente configurada (incluso si vacía).

2017-08-11 04:21 UTC, jsotuyod commented on src/configuration/XcodebuildConfiguration.php
> +        if ($this->otherFlags) {
no veo la declaración para este field en ningún lado...

2017-08-11 11:19 UTC, nsuarezml commented on src/configuration/XcodebuildConfiguration.php
> +        if ($this->otherFlags) {
Se me pasó, ya lo corregí.

2017-08-11 11:24 UTC, nsuarezml commented
Me pareció mejor que por defecto no esté el parámetro `-dry-run` porque cuando empecemos a utilizar frameworks dinámicos va a ser el caso más común.

2017-08-11 14:20 UTC, jsotuyod commented on src/configuration/XcodebuildConfiguration.php
> +        if ($this->otherFlags) {
si hacés `arc lint` sobre este proyecto estas cosas te las encuentra. arc lint over arc lint to get lint errors on your linters!

2017-08-11 14:31 UTC, jsotuyod commented
Ok, acá dejo entonces a @champo opinar. Yo me declaro ignorante.

2017-08-15 14:32 UTC, champo commented
mmm me suena un toque raro la verdad tener que hacer esto. Voy a estar haciendo un par de pruebas a ver por donde viene la mano.

2017-08-16 14:04 UTC, champo requested changes
Bien, estuve haciendo unas pruebas y me encontre con que esto introduce el problema de que necesitas hacer un clean antes para que funcione. Me parece que deberia o ser parte de la documentacion de alguna manera o ser parte del comando a ejecutar.

2017-08-16 19:23 UTC, nsuarezml commented
@champo Ahí lo cambié para que si NO se pasa el param `-dry-run` se haga un clean.
No estoy del todo convencido con el cambio, pero no encontré una mejor manera de hacerlo.

2017-08-18 19:54 UTC, champo approved these changes

2017-08-18 19:54 UTC, champo commented on src/configuration/XcodebuildConfiguration.php
> +        $this->otherFlags = $this->configurationManager->getConfigFromAnySource('xcodebuild.other-flags');
por que este cambio?

2017-08-18 19:55 UTC, champo commented
no encontre forma de evitar de esto de momento, me duele un toque por que sube los tiempos de build por deporte... pero bueno, vere si le logra dar una vuelta de tuerca, de momento es un parche aceptable

2017-08-18 20:22 UTC, nsuarezml commented on src/configuration/XcodebuildConfiguration.php
> +        $this->otherFlags = $this->configurationManager->getConfigFromAnySource('xcodebuild.other-flags');
Por que el parámetro `xcodebuild.other-flags` es opcional, puede ser nulo. El método `getConfigValue` lanza una excepción si no encuentra un valor para el parámetro buscado:
https://github.com/mercadolibre/arcanist-extensions/blob/1155c388a28116cb09b066c1be2e0d2c76352397/src/configuration/XcodebuildConfiguration.php#L48-L53

2017-08-18 20:35 UTC, nsuarezml commented
@champo @jsotuyod Gracias por revisarlo. A mi tampoco me convence esta solución, pero creo que es lo mejor por el momento y nos permite seguir avanzando. En cuanto tengamos un poco de tiempo vamos a revisarlo nuevamente.

2017-08-28 14:25 UTC, merged